### ISSUE TITLE
Design interface

### ISSUE THREAD

**Issue by bbarker** [labordynamicsinstitute/metajelo-ui#2]
Current plans:

* Tabbed interface with different sections
  - Tab will visually indicate completion in some manner
* Partially completed data can be [stored locally](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage):
  - user will be alerted that data will only be stored locally and not saved online (at least for now; can perhaps integrate with free cloud storage systems later)
  - user will be given the option to delete files from local storage once completed.
  - **need to serialize partially completed data**
    - easiest way would probably be to just save what is in the forms rather than serialize and read partial metajelo data, and re-parse - this has the advantage of using the latest application as well should there be an update. Though for the latter, see [here](https://pursuit.purescript.org/packages/purescript-foreign-generic/10.0.0).
  - see also:
     - [w3c web storage](https://www.w3.org/TR/webstorage/)
     - [purescript-web-storage](https://pursuit.purescript.org/packages/purescript-web-storage)
* For cloud storage, [Google Drive via JavaScript](https://developers.google.com/api-client-library/javascript/start/start-js) is likely a good option.

**Comment by bbarker** [comment]
I'm currently leaning towards a single-page interface, but could switch to a tabbed interface without too much trouble.

**Comment by larsvilhuber** [comment]
No opinion.

--
Lars Vilhuber
on mobile device

________________________________

**Comment by bbarker** [comment]
With regard to the first point above, I think we are leaving that to the UX designer and 3rd parties  to do as they see fit.
