### ISSUE TITLE
Explore packaging as an Electron application

### ISSUE THREAD

**Issue by bbarker** [labordynamicsinstitute/metajelo-ui#72]
Since electron apps can make use of Node libraries as well as run a chromium-based browser window, this seems to be the modern way to go. There was a modern-Firefox equivalent but it quickly became stagnant (https://github.com/mozilla/positron).  We can look at Zotero for inspiration, though this now uses relatively old browser technology (Gecko).

**Comment by larsvilhuber** [comment]
Seems fine to me, and that was the framework I was looking to name (VSCode and Atom are my regular interfaces to it)

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by bbarker** [comment]
Perhaps it is worth mentioning this alternative as well (at least some people may be interested in this route; I plan to use it in the development process if it becomes necessary): https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino?hl=en

**Comment by bbarker** [comment]
Speaking of browser extensions, building a Metajelo browser extension should be at least as general as having an Electron app. Chrome can run in more places than Electron (e.g., Chromebooks without X11 installed, which is most of them), and it is lighter weight than downloading a separate app. 

See here for more notes on the HTTP request API for extensions: https://developer.chrome.com/extensions/xhr

**Comment by bbarker** [comment]
Closing for now, as we don't need it (at least for DataCite).
